### ISSUE TITLE
Question : Page par défaut ?

### ISSUE THREAD

**Issue by LeOSW42** [YunoHost-Apps/multi_webapp_ynh#1]
Bonjour,

J'ai installé cette appli et le FTP qui va avec, mais une question demeure.
Que je vais à l'URL de l'appli, j'ai la page "Welcome to nginx".

Seulement quand je vais dans le FTP, l'index.html accessible est celle avec la page aléatoire du chat.
Où est le problème ? Dans l'appli FTP qui m'ouvre pas le bon dossier ou dans l'appli my_webapp qui n'affiche pas le bon index ?

Léo

**Comment by LeOSW42** [comment]
Le fichier de conf nginx a deux problèmes :

Il est nommé `.conf`
Il fait un alias vers `mywebapp_toto//` lorsqu'on place l'appli dans /

**Comment by maniackcrudelis** [comment]
Je jette un coup d'oeil en ce moment même ;)

**Comment by LeOSW42** [comment]
Alors pour t'aider, éditer ce fichier de conf et enlever le double / corrige tout et on a bien les chats qui reviennent.

**Comment by maniackcrudelis** [comment]
Ok, je comprend. Ce sont les lignes 10 et 11 qui provoquent ça:
https://github.com/maniackcrudelis/my_webapp_ynh/blob/master/scripts/install#L10-L11

Je suppose donc que tu as installé directement à la racine en mentionnant / comme chemin.
Toutefois, si je ne fais pas erreur (et si ça n'a pas changé), il est déconseillé d'installer une application à la racine de la sorte, car ça empêche toute installation d'autre applications.

Bon je constate que c'est indiqué lors de l'installation à la racine, donc tout va bien, pas de risque d'erreur.
Je vais implémenter ce cas particulier.

**Comment by LeOSW42** [comment]
Oui, dans mon cas toutes les applis sont dans admin.domaine.tld et domaine.tld recoit juste une webapp a la racine.

**Comment by maniackcrudelis** [comment]
C'est implémenté.
C'est un cas qui n'était pas prévu.
