### ISSUE TITLE
No 'mail' function on Raspbian Jessie

### ISSUE THREAD

**Issue by Jaxom99** [YunoHost-Apps/multi_webapp_ynh#13]
Hello,

I tried to install the webapp on my RPi 3 with latest Yunohost (2.7.9). The app was already installed (for a year or so) on another path of the same domain.
This installation  failed and auto-removed, with the error :
```
_common.sh: line 569: mail: command not found"
_common.sh: line 569: echo: write error: Broken pipe
```
The faulty command is as follow :
``` echo "$mail_message" | mail -a "Content-Type: text/plain; charset=UTF-8" -s "$mail_subject" "$recipients"```
 Curiously, although I use the mail server normaly, there is no "mail" command on the system. Is this a normal behaviour ?

Thanks in advance for the fix, I remain available for further details.

**Comment by maniackcrudelis** [comment]
Please just install mailutils with apt, it will fix it

**Comment by Jaxom99** [comment]
Thanks for the quick answer, I did it indeed. How come it was a) not in my install (raspbian jessie + YNH) and b) not detected as missing by the script when checking dependencies ?

Anyway thanks again, and I hope mailutils doesn't break anything in YNH !

**Comment by maniackcrudelis** [comment]
Mailutils is a standard package in debian, so usually we don't have to add it as a dependency.
But, unfortunately, it seems to not be standard in raspbian...
This package isn't a dependency of this app but of a generic function used by many apps.
So it's about to be added to YunoHost dependencies, currently in the unstable release.

**Comment by Jaxom99** [comment]
Ok, I got it. Seems ufortunate indeed, so I guess this bug report was somehow useful then.
