### ISSUE TITLE
Error in installation

### ISSUE THREAD

**Issue by workbykiran** [YunoHost-Apps/multi_webapp_ynh#14]
When tried installing this app, the installation process gave an error while creating an user.
I tried installing this app on a fresh installation in virtualbox image server locally.
Attached is the log for reference.
[multi_webapp_ynh.txt](https://github.com/YunoHost-Apps/multi_webapp_ynh/files/1733107/multi_webapp_ynh.txt)

**Comment by maniackcrudelis** [comment]
Your error is `useradd: invalid user name 'webapp_devserver.com_Testwebapp'`
But unfortunately, I tried to install this app on a VM with the same domain and path than you, and it works fine.
I don't know why the user name is invalid for you.

**Comment by workbykiran** [comment]
i tried opening with ipaddress in browser url instead of domain name and then tried installing the same and was successful. however with the domain name based login into yunohost, it failed.

**Comment by maniackcrudelis** [comment]
I don't know what to say. I've never seen that before.

**Comment by workbykiran** [comment]
I believe it works when we have actual domain rather than mimic one. i will close this issue.
