### ISSUE TITLE
https par défaut ?

### ISSUE THREAD

**Issue by LeOSW42** [YunoHost-Apps/multi_webapp_ynh#2]
Rebonjour,

Je pense que pour une appli de ce genre, on devrait enlever la redirection en https automatique.

Léo

**Comment by maniackcrudelis** [comment]
C'est un choix par défaut, je préfère que ce soit sécurisé par défaut plutôt que l'inverse. Ignorant ce que contiendra la webapp.

Tu peux toutefois aisément retirer la redirection automatique.

Ce sont ces 3 lignes:
https://github.com/maniackcrudelis/my_webapp_ynh/blob/master/conf/nginx.conf#L3-L5

```
if ($scheme = http) {
rewrite ^ https://$server_name$request_uri? permanent;
}
```
