### ISSUE TITLE
Error when installing the app

### ISSUE THREAD

**Issue by supermamie** [YunoHost-Apps/multi_webapp_ynh#22]
(sorry for the bad title)

I already have one site configured with this app and wanted to create a new one.
The 1st one has it's own full domain (e.g. https://something.myserver.fr/), but the one I want to create now should be in a sub-path in another domain (e.g. https://divers.myserver.fr/simple-proxy/).

Here is the error log in yunohost
https://paste.yunohost.org/raw/ogotiluwuk

**Comment by maniackcrudelis** [comment]
As you can see into the log, `useradd` doesn't like the `-` into the user name.
This is from the path.
This should be fixed into the package to not be blocked by allowed path, being not allowed user name.

Meanwhile, could you use a `_` instead ? It would work.

Please keep this issue open though, so I could fix it when I have time.

**Comment by supermamie** [comment]
I tried even without any special char in the path or in the name, and the installer still generate an invalid name.

https://paste.yunohost.org/raw/igixurodup

**Comment by maniackcrudelis** [comment]
Try with this branch please.
https://github.com/YunoHost-Apps/multi_webapp_ynh/tree/fix_useradd

We'll find the correct way to pass through useradd.

**Comment by supermamie** [comment]
I don't know why but I tried again today (without the branch first), and it worked :man_shrugging:
