### ISSUE TITLE
Problème à l'installation

### ISSUE THREAD

**Issue by nibreh** [YunoHost-Apps/multi_webapp_ynh#3]
Bonjour

Je ne parviens pas à installer plusieurs instance. En effet, j'obtiens les infos suivantes après installation ... étrange. Je précise que j'ai précédemment installé puis supprimé l'app qui est proposé officiellement par Yunohost.

ID my_webapp
Description App vide avec un accès FTP au répertoire Web
Multi instance Non

cordialement

**Comment by maniackcrudelis** [comment]
Bonjour,

Il y a peut-être un conflit d'ID entre la cette app et la webapp officielle. En effet, a l'origine, il était prévu de merger celle-ci avec l'officielle.  
Vérifie toutefois qu'il n'y ai aucun résidu de l'app officielle dans /etc/yunohost/app/

Pour ma part, je vais changer l'ID, car le merge semble avoir été oublié...

**Comment by nibreh** [comment]
Re-

C'est OK ça fonctionne maintenant

MERCI!
