### ISSUE TITLE
welcome to nginx on debian

### ISSUE THREAD

**Issue by adrien80080** [YunoHost-Apps/multi_webapp_ynh#4]
Hello ! 
j'ai installé cette application à la racine du domaine (ex :  dad.domain.tld)
mais j'ai une page NGinx : https://img.abhd.fr/ScCbzGGW/9Mc0WSY7

Je ne sais pas d'ou ça peut venir :/
Une idée ?

**Comment by maniackcrudelis** [comment]
Salut,

je vois que c'est un problème que tu as avec de nombreuses app.
As-tu vérifier le contenu des logs?

Il est peut probable que le problème viennent d'un package, c'est sûrement un problème de configuration au sein de ton système.

**Comment by maniackcrudelis** [comment]
https://github.com/maniackcrudelis/my_webapp_ynh/commit/e47805375c9848084e2948ac36803f237fec83a6

**Comment by maniackcrudelis** [comment]
Le problème de page blanche provient de la mise à jour récente de nginx.
C'est corrigé dans ce commit, https://github.com/maniackcrudelis/my_webapp_ynh/commit/e47805375c9848084e2948ac36803f237fec83a6
